# Generated by Django 5.0.6 on 2024-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villanvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
