# Generated by Django 5.0.6 on 2024-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villan', '0002_villanvariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='villanvariety',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
